name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2022-05-25
version: '9.3.14'
project: 'drupal'
datestamp: 1653506388
